<template><Teleport to="body"><div v-if="bg.open" class="onboarding-backdrop"><section ref="dialog" class="background-onboarding" role="dialog" aria-modal="true" aria-labelledby="onboard-title" @keydown.tab="trap"><header><span>{{step}} / 3</span><b>Aureon</b><span class="onboard-label">Настройка фона</span></header><div v-if="step===1" class="welcome-step"><img class="welcome-art" src="/backgrounds/liquid-violet.png" alt=""/><div><h1 id="onboard-title">Добро пожаловать<br>в Aureon</h1><p>Выберите фон для приложения.<br>Позже его можно поменять в настройках.</p><button class="setup-primary" type="button" @click="step=2">Выбрать фон <span>→</span></button><button class="setup-link" type="button" @click="bg.finish()">Пропустить настройку</button></div></div><template v-else-if="step===2"><div class="setup-heading"><h1 id="onboard-title">Какой фон использовать?</h1><p>Живой фон требует больше ресурсов. Выберите подходящий вариант.</p></div><GpuRecommendation/><BackgroundChoices recommendation/><div class="setup-footer"><button class="btn" type="button" @click="step=1">← Назад</button><button class="setup-primary" type="button" @click="chooseStyle">Далее →</button></div></template><template v-else><div class="setup-heading"><h1 id="onboard-title">Выберите цвет и рисунок</h1><p>{{bg.mode==='beauty'?'Живой фон':'Простой фон'}}</p></div><BackgroundPresets/><BackgroundPreview compact/><div class="setup-footer"><button class="btn" type="button" @click="step=2">← Назад</button><button class="setup-primary" type="button" @click="bg.finish()">Готово</button></div></template><p v-if="bg.error" role="alert" class="setup-error">{{bg.error}}</p></section></div></Teleport></template>
<script setup lang="ts">
import {ref,watch,nextTick,onBeforeUnmount} from 'vue';import {useBackgroundStore} from '@/stores/background';import BackgroundChoices from './BackgroundChoices.vue';import BackgroundPresets from './BackgroundPresets.vue';import BackgroundPreview from './BackgroundPreview.vue';import GpuRecommendation from './GpuRecommendation.vue';
const bg=useBackgroundStore();const step=ref(1);const dialog=ref<HTMLElement|null>(null);let previous:HTMLElement|null=null;
function chooseStyle(){if(bg.mode==='beauty'&&!['Black Chrome','Liquid Metal','Liquid Violet','Silver Metal','Dark Chrome','Purple Chrome','Midnight Metal','Gold Chrome'].includes(bg.preset))bg.selectPreset('Black Chrome');if(bg.mode==='optimized'&&!['gold','chrome','violet','ice','emerald'].includes(bg.preset))bg.selectPreset('chrome');step.value=3}
function trap(event:KeyboardEvent){const controls=dialog.value?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]');if(!controls?.length)return;const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}
watch(()=>bg.open,async open=>{if(open){previous=document.activeElement as HTMLElement;step.value=1;await nextTick();dialog.value?.querySelector('button')?.focus()}else previous?.focus()},{immediate:true});
watch(step,async()=>{await nextTick();dialog.value?.querySelector('button')?.focus()});onBeforeUnmount(()=>previous?.focus());
</script>
